### ISSUE TITLE
N2D2 Cross Compilation

### ISSUE THREAD

**Issue by moelyaagoubi** [CEA-LIST/N2D2#102]
After the cross-compilation from host (Ubuntu machine 18.04 x64_64) to target (NVIDIA DRIVE AGX aarch64), I was able to generate the N2D2.so file compatible with aarch64. 
However when I tried to do an import with Python3 (on the target), I got segmentation fault (core dumped).

**Comment by davidbriand-cea** [comment]
This requiest have been fixed by mail. 
The N2D2 TensorRT export is compatible with the cross-compilation NVidia environment for Drive AGX but 
required some modification to the Exported Makefile.
Typically  CUDA_PATH Makefile parameter should linked to the aarch64 cross-compilation CUDA environment.

Additional informations can be found here : 
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#cross-compilation

I close the issue, feel free to reopen it
