### ISSUE TITLE
[Windows] pgnuplot.exe not recognized

### ISSUE THREAD

**Issue by GuillaumeSutra** [CEA-LIST/N2D2#17]
On Windows, when I run the learning on mnist:
`./n2d2 "mnist24_16c4s2_24c5s2_150_10.ini" -learn 600000 -log 10000`
I get many non-fatal errors in console output:
`'pgnuplot.exe' is not recognized as an internal or external command`

Indeed the folder gnuplot/bin contains `wgnuplot.exe` and `gnuplot.exe` but no `pgnuplot.exe`.

Can you fix it in file Gnuplot.cpp ?
```
#ifdef WIN32
        mCmdPipe = _popen("pgnuplot.exe", "w");
#else
        mCmdPipe = popen("gnuplot", "w");
#endif
```

**Comment by olivierbichler-cea** [comment]
pgnuplot.exe was needed in old versions of gnuplot, but has been deprecated since at least gnuplot 4.5 and removed entirely in gnuplot 5.0.
gnuplot 4.5 was introduced in 2012... the gnuplot.exe command is here for some time already, so it doesn't seem necessary to maintain backward compatibility with pgnuplot.exe.
