### ISSUE TITLE
Building without CUDA?

### ISSUE THREAD

**Issue by baristahell** [CEA-LIST/N2D2#2]
Hi
I'm trying to build N2D2 in CPU-only mode but can't de-activate the automatic CUDA build. 
Is there a way to make without CUDA?
Thanks.

EDIT : Ok nevermind, there's a hidden USE_CUDA parameter.
You can build without CUDA by using
>cmake .. -DUSE_CUDA=0

**Comment by olivierbichler-cea** [comment]
Why do you want to build without CUDA?
If CUDA is not installed, it will not be detected by CMake and CUDA support will be automatically disabled.
If CUDA is installed on your machine, CUDA models will be also available.

Note that in either case, CPU-only models are always here. To simulate a network without CUDA acceleration, simply use the "Frame" models instead of the "Frame_CUDA" models (you can change the default model with the "DefaultModel" INI parameter).
