### ISSUE TITLE
Spike generator reference

### ISSUE THREAD

**Issue by vankhoa21991** [CEA-LIST/N2D2#42]
Hello, thanks for the support, I just want to know where is the reference paper for the Poissonian spike generator that you used in N2D2. 
As my understanding, the intensity is used to calculate the delay, and the variable delay will decide the periodmean is closer to the minmeanperiod or maxminperiod. Please correct me if I'm wrong. Thank you

**Comment by olivierbichler-cea** [comment]
Hi,
The delay is simply 1-value (so that with images, the brightness values, the white pixels, have the minimum delay. Also, at this point, value is already in the range [0,1] for 8 bit images if you didn't do any Transformation). The average frequency is then directly proportional to the delay, with a delay of 0 = max. frequency = 1/mPeriodMeanMin and delay of 1 = min. frequency = 1/mPeriodMeanMax.
Please note that in the current SpikeGenerator implementation, it is the frequency that is proportional to the value, not the period (this is for historical reason, but it actually makes more sense to have the period proportional to the value when converting DNN to SNN... the current behavior should probably change in the future)!
Finally, to generate the Poissonian spikes, one just has to know that the time between arrivals in a Poisson process is exponentially distributed...

**Comment by vankhoa21991** [comment]
Thanks for your answer, just another question about the code, in the exponential function of the Poissonian, I saw that you select the period = periodMean* log (Uniform (0,1)), so why it is a log, not an exponential?

**Comment by vankhoa21991** [comment]
Thanks for your answer, just another question about the code, in the exponential function of the Poissonian, I saw that you select the period = periodMean* log (Uniform (0,1)), so why it is a log, not an exponential?
